export const strings = {
  title: 'Peso Coach',
  today: 'Hoje',
  date: 'Data',
  morning: 'Peso manhã (kg)',
  night: 'Peso noite (kg)',
  save: 'Salvar',
  week: 'Semana',
  mean7d: 'Média 7d',
  weeklyChange: 'Variação semanal',
  statusVsCheckpoint: 'Status vs checkpoint',
  goalsProjection: 'Metas & Projeção',
  recalc: 'Recalcular',
  restoreDefaults: 'Restaurar padrões',
  charts: 'Gráficos',
  data60d: 'Dados (60 dias)',
  edit: 'editar',
  backup: 'Backup',
  exportJSON: 'Exportar JSON',
  importJSON: 'Importar JSON',
  workerURL: 'Worker URL',
  bearerToken: 'Bearer Token',
  backupWorker: 'Backup (Worker)',
  restoreWorker: 'Restore (Worker)',
  checkpoints: 'Definições de Checkpoints',
  add: 'Adicionar',
  cancel: 'Cancelar'
};

